### 주소 좌표값 변환 api
GET https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query=강남대로 396
X-NCP-APIGW-API-KEY-ID: {{naver-map-client-id}}
X-NCP-APIGW-API-KEY: {{naver-map-client-secret}}


### 자동차 경로 계산 api
GET https://naveropenapi.apigw.ntruss.com/map-direction-15/v1/driving?start=127.1058342,37.359708&goal=126.9284261,37.5258975
X-NCP-APIGW-API-KEY-ID: {{naver-map-client-id}}
X-NCP-APIGW-API-KEY: {{naver-map-client-secret}}